# -*- coding: utf-8 -*-
"""Fire_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_ACHKdW7OI_eUulcZfpRwE-QB89X_p5
"""

from google.colab import files
uploaded = files.upload()

import zipfile

zip_path = "flame_detection_file.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/dataset")

!pip install ultralytics

from ultralytics import YOLO


model = YOLO("yolov8n.pt")


model.train(
    data="/content/dataset/Flame/data.yaml",
    epochs=50,
    imgsz=640
)

model = YOLO("/content/runs/detect/train/weights/best.pt")

model.predict(
    source="/content/dataset/Flame/test/images",
    conf=0.5,
    save=True
)

from IPython.display import Image, display
import os

folder = "/content/runs/detect/predict"

for img in os.listdir(folder)[:5]:  # show 5 images
    display(Image(filename=os.path.join(folder, img)))

metrics = model.val()

print(f"mAP50 (Accuracy): {metrics.box.map50:.3f}")
print(f"mAP50-95: {metrics.box.map:.3f}")
print(f"Precision: {metrics.box.mp:.3f}")
print(f"Recall: {metrics.box.mr:.3f}")