# -*- coding: utf-8 -*-
"""Sound_sensor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h1I7JA7HBEDBOog-Gj9IDEPnXBsl7Ogq
"""

!pip install librosa numpy scikit-learn

import os
import numpy as np
import librosa
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, accuracy_score

from google.colab import files
uploaded = files.upload()

import zipfile
zip_name = list(uploaded.keys())[0]
with zipfile.ZipFile(zip_name, 'r') as z:
    z.extractall('/content/scream_data')


import os
for root, dirs, files_list in os.walk('/content/scream_data'):
    level = root.replace('/content/scream_data', '').count(os.sep)
    if level < 2:
        print(root)
        for d in dirs:
            print(f"   {d}")

import os
import numpy as np
import librosa

def extract_mfcc(file_path):
    try:
        y, sr = librosa.load(file_path, duration=3.0, sr=22050)
        mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)
        return np.hstack([mfcc.mean(axis=1), mfcc.std(axis=1)])
    except Exception as e:
        print(f"Error: {file_path} — {e}")
        return None

X = []
y = []

base = '/content/scream_data/archive (1)'

labels = ['scream', 'non_scream']

for label in labels:
    folder = os.path.join(base, label)

    if not os.path.exists(folder):
        print(f"Folder not found: {folder}")
        continue

    print(f"Loading {label}...")
    count = 0
    for file in os.listdir(folder):
        if file.endswith('.wav'):
            file_path = os.path.join(folder, file)
            features = extract_mfcc(file_path)
            if features is not None:
                X.append(features)
                y.append(label)
                count += 1

    print(f"  Loaded {count} files from {label}")

print(f"\nTotal samples: {len(X)}")

X = np.array(X)
y = np.array(y)

print("Dataset loaded:", X.shape)

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42
)

model = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=500)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))